Final: Capstone PR
wwwdrt/capstone pull request #10
Opened 2023-04-29 16:18 UTC by wwwdrt

# 🎯Learning objectives

- Understand how to use medium-fidelity wireframes to create a UI.
- Follow written requirements (e.g. user stories).
- Use semantic HTML tags.
- Apply best practices in HTML code.
- Use CSS selectors correctly.
- Use CSS box model.
- Use Flexbox to place elements in the page.
- Use images and backgrounds to enhance the look of a website.
- Demonstrate ability to create UIs adaptable to different screen sizes using media queries.
- Use GitHub Pages to deploy web pages.
- Apply JavaScript best practices and language style guides in code.
- Use JavaScript to manipulate DOM elements.
- Use JavaScript events.
- Use objects to store and access data.
- Communicate technical concepts to other technical people.

# 🚀Overview

In this capstone project, you are going to build is based on an online website for a conference. We provide some design guidelines for you to create the website, but you must personalize the content, i.e., instead of a conference you can build a website for a concert or for a web development course. It's very important you personalize your project so that you have something unique in your portfolio to share with potential employers during job searching.

# 📃General requirements

- [ ] Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
- [ ] Make sure that you used correct [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md).
- [ ] Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

# 📃HTML/CSS & JavaScript requirements

- [ ] Follow our list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
- [ ] Follow our list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).

# 📃Project requirements

- [ ] You should personalize the content of your page. Choose a topic that is different than the one in the original design.
- [ ] You should follow these [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), including:
- [ ] Colors.
- [ ] Typography: font face, size and weight (we suggest using [Lato](https://www.latofonts.com/) as it is a free font similar to the one used in the original design).
- [ ] Layout: composition and space between elements.
- [ ] The pages should look almost identical to the original design. Small adjustments like text or image changes are acceptable.
- [ ] You can use a CSS framework (for example Bootstrap) for styling, if you want to.
- [ ] You should build only home and about pages.
- [ ] Mobile: up to 768px wide.
- [ ] Desktop: 768px or wider.
- [ ] The home page should have a link in the menu to the about page.
- [ ] The logo in the header links to the home page.
- [ ] When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
- [ ] There are no guidelines for the mobile menu in the docs, but you should implement it so it is consistent with the design (colors, typography, spacings, etc.).
- [ ] The mobile menu should have a close (X) button that closes the menu.
- [ ] The section "Featured speakers" should be created dynamically in JavaScript.
- [ ] You should use a JavaScript variable with the data about the speakers and use it when the page loads to create the HTML for this section dynamically.
- [ ] The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project.

# 📃Project documentation

Once you have finished the development of the project, you should record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes. The content of the video should include:

- [ ] A description of the project.
- [ ] A demo of the project features (different pages and different screen sizes).
- [ ] You should also highlight some interesting piece of code or something you built that you are very proud of.
- [ ] For recording the video you can use tools like [Loom](https://www.loom.com/) that let you share a private link to the recording, and configure a shot that shows your computer screen and your face at the same time in a small picture.
- [ ] Add the video link to your pull request description.

# 📝Note

👋Hey, I'm looking forward to your feedback.

2023-04-29 23:06 UTC, tufoinnkuo10 requested changes
Hi @wwwdrt 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ Mobile menu hamburger works as expected
✅ design well followed

video presentation
Great job with the code presentation. please always give a nice reason why you build what you built and explanations when presenting your work rather than just clicking through. it will help some viewers understand more. nice work

Required Changes ♻️
Check the comments under the review

![tufoin](https://media.giphy.com/media/QW9DYS2fsdORhO9Phu/giphy.gif)

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-04-29 23:06 UTC, tufoinnkuo10 commented on index.html
> +                <img src="./public/logo.png" alt="Logo" class="h-[53px] w-[81px] mr-8 cursor-pointer">
- [ ] great job. please like in the original  design, kindly align the logo with the headline text and position the nav links a little to the right. nice work
yours
![Screenshot (1026)_LI](https://user-images.githubusercontent.com/65298048/235327033-a35a68d1-ef2b-41cb-9950-e46752610c39.jpg)
original
![Screenshot (1026)](https://user-images.githubusercontent.com/65298048/235327047-f56c2d7d-1057-4a94-9a9d-014ef6cb30d7.png)

2023-04-29 23:06 UTC, tufoinnkuo10 commented on index.html
> +                <li>
- [ ] please the Mobile home page does not have a logo on the headline section. it has thesame tiltles like in the desktop version. please follow the original design and fix that. 
yours
![Screenshot (1033)](https://user-images.githubusercontent.com/65298048/235327524-44dcf663-e1f0-4d12-92fa-041790157df5.png)
original
![Screenshot (1034)](https://user-images.githubusercontent.com/65298048/235327532-fc39051b-eb70-43fe-98e5-9b26e05bd64f.png)

2023-04-29 23:06 UTC, tufoinnkuo10 commented on index.html
> +                <p id="place" class="text-place mb-[6rem]">@ Sheikh Zayed Rd, Dubai World Trade Centre and more</p>
- [ ] your speakers section is not visible. please kindly fix that. both for the desktop and mobile version
![Screenshot (1027)](https://user-images.githubusercontent.com/65298048/235327170-aeabd3c4-7772-4624-abcc-6e570aa21e9c.png)

2023-04-29 23:06 UTC, tufoinnkuo10 commented on pages/about.html
> -            <img src="../capstone/public/logo.png" alt="Logo" class="h-[104px] w-[193px] m-auto">
- [ ] Grreat job with the about page . please kindly follow the design and personalize the content not add new design.please remove the video and make the logo to look like the original version.
yours
![Screenshot (1029)_LI](https://user-images.githubusercontent.com/65298048/235327296-88747b67-3e45-420a-bd76-1b66d6ef7e8a.jpg)
original
![Screenshot (1030)](https://user-images.githubusercontent.com/65298048/235327323-472377ae-7c4b-4d50-9b0d-7c6c5293d433.png)

2023-04-29 23:06 UTC, tufoinnkuo10 commented on pages/about.html
>          <hr class="hr">
- [ ]  please reduce the size /height of the partner section of the mobile about page so it looks like the original design
yours
![Screenshot (1031)](https://user-images.githubusercontent.com/65298048/235327379-73eca9f9-5470-4895-bc30-56de95d68d2e.png)
original
![Screenshot (1032)](https://user-images.githubusercontent.com/65298048/235327399-07ad2ea2-a48c-43d3-8b1d-1059c6a4636d.png)

2023-04-29 23:06 UTC, tufoinnkuo10 commented on pages/about.html
>      <div id="footer-info" class="flex flex-col gap-4 w-[80%] p-8">
- [ ] please reduce the height of the about desktop footer so it can match the original design
![Screenshot (1028)_LI](https://user-images.githubusercontent.com/65298048/235327228-35090b34-ac62-4b06-8234-959a918eaa29.jpg)

2023-04-29 23:22 UTC, wwwdrt commented on index.html
> +                <p id="place" class="text-place mb-[6rem]">@ Sheikh Zayed Rd, Dubai World Trade Centre and more</p>
This one is alright, GitHub pages is very slow 🫡

2023-04-29 23:29 UTC, wwwdrt commented on index.html
> +                <img src="./public/logo.png" alt="Logo" class="h-[53px] w-[81px] mr-8 cursor-pointer">
👉✅

<img width="944" alt="image" src="https://user-images.githubusercontent.com/100488248/235328147-c7816278-c17b-4ef7-aab5-8988e9763be4.png">

2023-04-29 23:36 UTC, wwwdrt commented on index.html
> +                <li>
👉✅
<img width="346" alt="image" src="https://user-images.githubusercontent.com/100488248/235328308-f0010ff4-14a1-4f71-9c99-7c413f44d2b1.png">

2023-04-29 23:46 UTC, wwwdrt commented on pages/about.html
> -            <img src="../capstone/public/logo.png" alt="Logo" class="h-[104px] w-[193px] m-auto">
👉✅

<img width="957" alt="image" src="https://user-images.githubusercontent.com/100488248/235328572-84ff2a5c-61a4-4ba2-929d-8ebb33fd899b.png">

2023-04-29 23:53 UTC, wwwdrt commented on pages/about.html
>          <hr class="hr">
👉✅

<img width="476" alt="image" src="https://user-images.githubusercontent.com/100488248/235328724-231e049d-1cde-4f95-b0b2-f63bcd043617.png">

2023-04-30 00:01 UTC, wwwdrt commented on pages/about.html
>      <div id="footer-info" class="flex flex-col gap-4 w-[80%] p-8">
👉✅

<img width="749" alt="image" src="https://user-images.githubusercontent.com/100488248/235328949-fc46204c-30a4-46d2-a7a6-93bad2980ef6.png">

2023-04-30 00:13 UTC, emmiiorji approved these changes
Hi @wwwdrt, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/235302769-ce229a42-ec41-4bed-b1ad-6ff4b9baed38.gif'/>
</div>


## Good Highlights✔️

- Requested changes have been implemented

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-30 17:03 UTC, merged